spring.application.name=pagape

# ===============================
# CONFIGURACIÓN DE CONEXIÓN A MYSQL
# ===============================
# Cambia "pagape_db" por el nombre real que le vayas a dar a tu base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/pagape_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# Tu usuario de MySQL (suele ser root en local)
spring.datasource.username=pagape_user

# Tu contraseña de MySQL
spring.datasource.password=pagape

# El driver que permite a Java hablar con MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA (MAGIA DE SPRING)
# ===============================
# "update" hace que Spring cree o modifique las tablas automáticamente basándose en tus clases de Java
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en la consola (súper útil mientras desarrollas)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Clave secreta para firmar los tokens JWT
jwt.secret=clave-jwt-secreta-pagape-dam-2026-peruanos

# Tiempo de expiración del token en milisegundos (86400000 = 24 horas)
jwt.expiration=86400000